// <auto-generated />
using System;
using Bouwmarkt_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bouwmarkt_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220423072109_KoopzondagDbSet")]
    partial class KoopzondagDbSet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Bouwmarkt_DataAccess.Koopzondag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DatumOpeningstijdTot")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumOpeningstijdVan")
                        .HasColumnType("datetime2");

                    b.Property<int>("VestigingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VestigingId");

                    b.ToTable("Koopzondagen");
                });

            modelBuilder.Entity("Bouwmarkt_DataAccess.Vestiging", b =>
                {
                    b.Property<int>("VestigingsNummer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VestigingsNummer"), 1L, 1);

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plaats")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefoonNummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VestigingsNummer");

                    b.ToTable("Vestigingen");
                });

            modelBuilder.Entity("Bouwmarkt_DataAccess.Koopzondag", b =>
                {
                    b.HasOne("Bouwmarkt_DataAccess.Vestiging", "Vestiging")
                        .WithMany("Koopzondagen")
                        .HasForeignKey("VestigingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vestiging");
                });

            modelBuilder.Entity("Bouwmarkt_DataAccess.Vestiging", b =>
                {
                    b.Navigation("Koopzondagen");
                });
#pragma warning restore 612, 618
        }
    }
}
